#!/bin/bash -e

bundle install

jazzy \
  --author 'Chris Araman' \
  --author_url https://github.com/chris-araman \
  --clean \
  --github_url https://github.com/chris-araman/CombineCloudKit \
  --github-file-prefix https://github.com/chris-araman/CombineCloudKit/tree/"$(git rev-parse HEAD)" \
  --module CombineCloudKit \
  --module-version "$(git describe --tags)" \
  --output docs \
  --theme fullwidth

# Restore GitHub Pages CNAME file
# https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#cname-errors
git checkout -- docs/CNAME
