#!/bin/bash -e

# Clean docs
rm -rf docs/CombineCloudKit.doccarchive/

# Build documentation using Xcode 13's DocC
# https://developer.apple.com/documentation/docc
xcodebuild docbuild -scheme CombineCloudKit -destination 'platform=macOS,arch=arm64' -derivedDataPath .build/docs/ -quiet
ditto .build/docs/Build/Products/Debug/CombineCloudKit.doccarchive/ docs/CombineCloudKit.doccarchive/
