#!/bin/bash -e

if [[ ! -x "$(command -v brew)" ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle install --no-lock --quiet >/dev/null

echo "⚙️  Linting CombineCloudKit..."

echo "  🧹 git"
git diff --check

echo "  🧹 markdownlint"
markdownlint --config .markdownlint.json --fix .github .

echo "  🧹 periphery"
periphery scan --quiet

echo "  🧹 pod"
pod lib lint --silent CombineCloudKit.podspec

echo "  🧹 prettier"
prettier --loglevel warn --write .

echo "  🧹 shellcheck"
SCRIPTS=(
  script/build_docs
  script/lint
)
shellcheck --shell=bash "${SCRIPTS[@]}"

echo "  🧹 shfmt"
shfmt -d -i 2 -l -w "${SCRIPTS[@]}"

echo "  🧹 swift-format"
SOURCES=(
  Package*.swift
  Sources
  Tests
)
swift format format --in-place --recursive "${SOURCES[@]}"
swift format lint --recursive "${SOURCES[@]}"

echo "✅ CombineCloudKit is free of lint!"
