name: Lint, Build, & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: ${{ matrix.action_name }} (${{ matrix.platform }}, Swift ${{ matrix.swift }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        swift: [5.1, 5.2, 5.3, 5.4]
        platform: [macOS, iOS, tvOS, watchOS]
        action_spm: [build, test]
        exclude:
          - swift: 5.1
            action_spm: test
          - swift: 5.2
            action_spm: test
          - swift: 5.3
            action_spm: test
          - swift: 5.4
            action_spm: build
        include:
          - action_spm: build
            action_xc: build
            action_name: Build
          - action_spm: test
            action_xc:
            action_name: Build & Test
          # TODO: We should be able to test watchOS with Swift 5.4, but we don't have access to Xcode 12.5 and macOS 11.
          - action_spm: test
            platform: watchOS
            swift: 5.4
            action_name: Build
          # The latest version of Xcode that supports each release of Swift.
          # https://developer.apple.com/support/xcode/
          - swift: 5.1
            xcode: ~11.3
          - swift: 5.2
            xcode: ~11.7
          - swift: 5.3
            xcode: ~12.4
          - swift: 5.4
            # TODO: Remove this once we have access to Xcode 12.5 and macOS 11.
            # xcode: ^12
            pkg: https://swift.org/builds/swift-5.4.1-release/xcode/swift-5.4.1-RELEASE/swift-5.4.1-RELEASE-osx.pkg
            toolchain: swift
    env:
      TOOLCHAINS: ${{ matrix.toolchain }}
    steps:
    - name: Clone
      uses: actions/checkout@v2
    # TODO: Remove this once we have access to Xcode 12.5 and macOS 11.
    - name: Install Swift ${{ matrix.swift }}
      if: ${{ matrix.pkg }}
      run: |
        curl -o swift.pkg '${{ matrix.pkg }}'
        sudo installer -pkg swift.pkg -target /
    - name: ${{ matrix.name }} for ${{ matrix.platform }} with xcodebuild
      uses: mxcl/xcodebuild@v1
      with:
        action: ${{ matrix.action_xc }}
        platform: ${{ matrix.platform }}
        xcode: ${{ matrix.xcode }}
    - name: Build & Test for ${{ matrix.name}} for macOS with Swift Package Manager
      if: ${{ matrix.platform == 'macOS' }}
      run: xcrun swift ${{ matrix.action_spm }}
  lint-sanitize-coverage:
    name: Lint, Sanitize, & Coverage
    runs-on: macos-latest
    env:
      TOOLCHAINS: swift
    steps:
    - name: Clone
      uses: actions/checkout@v2
    # TODO: Remove this once we have access to Xcode 12.5 and macOS 11.
    - name: Install Swift 5.4
      run: |
        curl -o swift.pkg 'https://swift.org/builds/swift-5.4.1-release/xcode/swift-5.4.1-RELEASE/swift-5.4.1-RELEASE-osx.pkg'
        sudo installer -pkg swift.pkg -target /
    - name: Lint
      run: script/lint
    - name: Address Sanitizer
      run: xcrun swift test --sanitize=address
    - name: Thread Sanitizer
      run: xcrun swift test --sanitize=thread
    - name: Undefined Behavior Sanitizer
      run: xcrun swift test --sanitize=undefined
    - name: Coverage
      run: |
        xcrun swift test --enable-code-coverage
        cd .build/$(uname -m)-apple-macosx/debug
        xcrun llvm-cov show -use-color -instr-profile=codecov/default.profdata CombineCloudKitPackageTests.xctest/Contents/MacOS/CombineCloudKitPackageTests > coverage.txt
        bash <(curl -s https://codecov.io/bash) -f coverage.txt -Z
